Прочитаем файл .mat

In [18]:
import scipy
import numpy as np
import pandas as pd

data = scipy.io.loadmat("../sources/Buckley_Swc_0_Sor_0_M_2.mat")

In [25]:
print(data.keys())

dict_keys(['__header__', '__version__', '__globals__', 't', 'usol', 'x'])


In [24]:
print(data['usol'])

[[1.         1.         1.         ... 1.         1.         1.        ]
 [0.         0.79307931 0.86958696 ... 0.99609961 0.99609961 0.99619962]
 [0.         0.69046905 0.79307931 ... 0.99219922 0.99229923 0.99239924]
 ...
 [0.         0.         0.         ... 0.64216422 0.64416442 0.64616462]
 [0.         0.         0.         ... 0.64146415 0.64346435 0.64536454]
 [0.         0.         0.         ... 0.64066407 0.64266427 0.64466447]]


In [ ]:
t = data['t'].flatten()[:,None]
x = data['x'].flatten()[:,None]
value = np.real(data['usol']).T

In [28]:
import matplotlib.pyplot as plt

In [ ]:
def simple_plot_x_slices(x, t, value):
    
    plt.figure(figsize=(12, 8))
    
    for i in range(len(t)):
        plt.plot(x, value[i, :], alpha=0.7, linewidth=0.8)
    
        plt.xlabel('x', fontsize=14)
        plt.ylabel('u(x,t)', fontsize=14)
        plt.title(f"Время {t[i]} с", fontsize=16)
        plt.grid(True, alpha=0.3)
        plt.show()

In [ ]:
simple_plot_x_slices(x, t, value)

TypeError: simple_plot_x_slices() missing 2 required positional arguments: 't' and 'value'